### PR TITLE
[CHANGE] abstract modifier

### PR DESCRIPTION
**Pull request by Panzenbaby**
Do not ignore the abstract modifier of your annotated class. The generated class has to be abstract as well and should have a abstract factory method.

### CODE REVIEW

**Comment by yshrsmz** [comment]
Could you elaborate on why you need this change?

**Comment by Panzenbaby** [comment]
I want to use a abstract class with abstract methods so I can extend from it.
But this will not work because the generated class is neither abstract nor can it create a new instance in the create method because of the missing implementation of the abstract methods.

**Comment by yshrsmz** [comment]
hmm
As stated in Single Responsibility Principle, I don't recommend you to mix different kind of logic in one class. 
What you are trying to achieve is, in my opinion, feasible by simply creating wrapper class of generated class.

**Comment by Panzenbaby** [comment]
Ok fine.

But if someone uses a abstract class with abstract methods the generated class wouldn't be compileable. Maybe you should throw a Exception at least.

**Pull request closed without merging**
